# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build Qt OHOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  windows-2025-build:

    runs-on: windows-2025

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: build
        run: |
          python ./build-qt-ohos.py --init
          python ./build-qt-ohos.py --exe_stage all --with_pack
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output-${{ matrix.os }}
          path: work/output/*.zip

  windows-2022-build:

    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: build
        run: |
          python ./build-qt-ohos.py --init
          python ./build-qt-ohos.py --exe_stage all --with_pack
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output-${{ matrix.os }}
          path: work/output/*.zip

  ubuntu-24-04-build:

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: build
        run: |
          python ./build-qt-ohos.py --init
          python ./build-qt-ohos.py --exe_stage all --with_pack
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output-${{ matrix.os }}
          path: work/output/*.tar.gz

  ubuntu-22-04-build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: build
        run: |
          python ./build-qt-ohos.py --init
          python ./build-qt-ohos.py --exe_stage all --with_pack
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output-${{ matrix.os }}
          path: work/output/*.tar.gz

  macOS-26-build:

    runs-on: macos-26

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: build
        run: |
          python ./build-qt-ohos.py --init
          python ./build-qt-ohos.py --exe_stage all --with_pack
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output-${{ matrix.os }}
          path: work/output/*.tar.gz

  macOS-15-build:

    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: build
        run: |
          python ./build-qt-ohos.py --init
          python ./build-qt-ohos.py --exe_stage all --with_pack
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output-${{ matrix.os }}
          path: work/output/*.tar.gz

  macOS-14-build:

    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: build
        run: |
          python ./build-qt-ohos.py --init
          python ./build-qt-ohos.py --exe_stage all --with_pack
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output-${{ matrix.os }}
          path: work/output/*.tar.gz
  

    
